[project]
name = "keystore"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=46.0.3",
    "jsonpickle>=4.1.1",
    "nicegui>=3.6.1",
    "pywebview>=6.1",
]
